name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    name: Check lint, formatting, and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust Node.js version as needed
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Build
        run: npm run build
